services:
  
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 64M
    networks:
      - traefik-public
      - docker-proxynet
    ports:
      - "80:80"
      - "443:443"
    environment:
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
      - TZ=Asia/Kolkata
      - TRAEFIK_DASHBOARD_CREDENTIALS=${TRAEFIK_DASHBOARD_CREDENTIALS}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./configs/traefik.yaml:/traefik.yaml:ro
      - ./configs/config.yaml:/config.yaml:ro
      - ./data/acme-cf.json:/acme-cf.json
      - traefik-logs:/var/log/traefik 
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`${TRAEFIK_DASHBOARD_HOST:?No TRAEFIK_DASHBOARD_HOST set}`)"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.middlewares.dashboard-auth.basicauth.users=${TRAEFIK_DASHBOARD_CREDENTIALS:?No TRAEFIK_DASHBOARD_CREDENTIALS set}"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.tls.certresolver=${TRAEFIK_CERT_RESOLVER:?No TRAEFIK_CERT_RESOLVER set}"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.middlewares=dashboard-auth"

  socket-proxy:
    image: lscr.io/linuxserver/socket-proxy:latest
    container_name: socket-proxy
    environment:
      - CONTAINERS=1
      - EVENTS=1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - docker-proxynet
    restart: always
    read_only: true
    tmpfs:
      - /run
      

volumes:
  traefik-logs:
    name: traefik-logs 

networks:
  traefik-public:
    name: traefik-public
    external: false